# Spring配置（Mail、MySQL、Redis）
spring:
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DB:uim}?characterEncoding=${MYSQL_CHARSET:utf8}&useSSL=${MYSQL_SSL:false}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 3
      minimum-idle: 1
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  mail:
    host: ${SMTP_HOST:smtp.exmail.qq.com}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
# 日志输出 cn.dustlight.oauth2.uim.mappers
logging:
  level:
    cn:
      dustlight:
        oauth2:
          uim:
            mappers:
              GrantTypeMapper: debug
              ClientMapper: debug
            controllers:
              code:
                DefaultVerificationCodeController: debug
              users:
                DefaultUserBaseController: debug
                DefaultUserExtendController: debug
# Mybatis
mybatis:
  configuration:
    cache-enabled: false
    local-cache-scope: statement

# SpringDoc
springdoc:
  api-docs:
    path: /api/v1
  swagger-ui:
    path: /api/doc/
# 应用配置
dustlight:
  uim:
    public-paths:
      - /api/doc/**
    resource-paths:
      - /api/res/**
    storage:
      storage-base-url: https://res.dustlight.cn/
  storage:
    tencent:
      cos:
        enabled: true
        secret-id: ${TENCENT_COS_SECRET_ID}
        secret-key: ${TENCENT_COS_SECRET_KEY}
        bucket: ${TENCENT_COS_BUCKET}
        region: ${TENCENT_COS_REGION}
        http-protocol: https