# Spring配置（Mail、MySQL、Redis）
spring:
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/oauth?characterEncoding=utf8&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 4
      minimum-idle: 1
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  mail:
    host: ${SMTP_HOST:smtp.exmail.qq.com}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
# 日志输出
logging:
  level:
    cn:
      dustlight:
        uim:
          services:
            ClientDetailsMapper: debug
            TemplateManagerMapper: debug
            UserDetailsMapper: debug
# Mybatis 缓存
mybatis-plus:
  configuration:
    cache-enabled: true
    local-cache-scope: session
# SpringDoc
springdoc:
  api-docs:
    path: /api/doc/v3
  swagger-ui:
    path: /api/doc/swaager-ui
# 应用配置
dustlight:
  uim:
    csrf-enabled: false
    public-paths:
      - /api/user/code/**
      - /api/user/verify/**
      - /api/user/exists/**
      - /api/user/login
      - /api/user/register
      - /api/user/reset/email/password
      - /api/user/avatar/**
      - /api/client/app_image/**
      - /api/doc/**
      - /api/pub/**
      - /oauth/check_token
      - /oauth/token
    resource-paths:
      - /oauth_info
      - /api/res/**
    form-login:
      login-page: /login
      login-processing-url: /api/user/login
    logout:
      logout-url: /api/user/logout
      delete-cookies:
        - SESSION
    register-email: 邮箱验证
    reset-password-email: 密码重置
  storage:
    tencent:
      cos:
        enabled: true
        secret-id: ${TENCENT_COS_SECRET_ID}
        secret-key: ${TENCENT_COS_SECRET_KEY}
        bucket: ${TENCENT_COS_BUCKET}
        region: ${TENCENT_COS_REGION}
        http-protocol: https